[package]
name = "peer-fs"
version = "0.1.0"
authors = ["Niraj Nepal <niraj@gurzu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
